{% set name = "libnvjitlink" %}
{% set version = "12.0.76" %}
{% set cuda_version = "12.0" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/{{ name }}/{{ platform }}/{{ name }}-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 92a70db1ee90f1816a40d4d2019e0a59c43eebb9f3eb1208abedcc00a13e48be  # [linux64]
  sha256: dd317e1d052b4231ab95d1b472105640f617f7d250aacc5bc1c952aab93d7483  # [ppc64le]
  sha256: 9f18090f6587e95be0ee424f07358eeb0e15c5ab3f8636870f68dd84a92ed2e6  # [aarch64]
  sha256: cae74b6790174b283d892bb20e1ff91bff13c8a2a8486de4f417e09675469372  # [win]

build:
  number: 2
  binary_relocation: false
  skip: true  # [osx]

test:
  requires:
    - patchelf  # [linux]
  files:
    - test-rpath.sh
  commands:
    - test -L $PREFIX/lib/libnvJitLink.so.{{ version.split(".")[0] }}                            # [linux]
    - test -L $PREFIX/lib/libnvJitLink.so.{{ version }}                                          # [linux]
    - test -L $PREFIX/targets/{{ target_name }}/lib/libnvJitLink.so.{{ version.split(".")[0] }}  # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/lib/libnvJitLink.so.{{ version }}                # [linux]
    - bash test-rpath.sh                                                                         # [linux]
    - if not exist %LIBRARY_BIN%\nvJitLink*.dll exit 1                                           # [win]

outputs:
  - name: libnvjitlink
    files:
      - lib/libnvJitLink.so.*                            # [linux]
      - targets/{{ target_name }}/lib/libnvJitLink.so.*  # [linux]
      - Library\bin\nvJitLink*.dll                       # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - sysroot_{{ target_platform }} 2.17    # [linux]
        - patchelf <0.18.0                      # [linux]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    # Tests are defined at the top level, due to package/output name conflicts.
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA nvJitLink library
      description: |
        nvJitLink - Just-in-Time Link Time Optimization (JIT LTO)
      doc_url: https://docs.nvidia.com/cuda/nvjitlink/

  - name: libnvjitlink-dev
    build:
      run_exports:
        - {{ pin_subpackage("libnvjitlink", max_pin="x") }}
    files:
      - lib/libnvJitLink*.so                            # [linux]
      - lib/pkgconfig                                   # [linux]
      - targets/{{ target_name }}/include/nvJitLink.h   # [linux]
      - targets/{{ target_name }}/lib/libnvJitLink*.so  # [linux]
      #- targets/{{ target_name }}/lib/stubs             # [linux]  # bug: currently missing
      - Library\include                                 # [win]
      - Library\lib\nvJitLink.lib                       # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - sysroot_{{ target_platform }} 2.17    # [linux]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("libnvjitlink", exact=True) }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - libnvjitlink-static >={{ version }}
    test:
      commands:
        - test -L $PREFIX/lib/libnvJitLink.so                            # [linux]
        - test -f $PREFIX/lib/pkgconfig/nvjitlink*.pc                    # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/nvJitLink.h  # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libnvJitLink.so  # [linux]
        - if not exist %LIBRARY_INC%\nvJitLink.h exit 1                  # [win]
        - if not exist %LIBRARY_LIB%\nvJitLink.lib exit 1                # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA nvJitLink library
      description: |
        nvJitLink - Just-in-Time Link Time Optimization (JIT LTO)
      doc_url: https://docs.nvidia.com/cuda/nvjitlink/index.html

  - name: libnvjitlink-static
    files:
      - targets/{{ target_name }}/lib/libnvJitLink*_static.a  # [linux]
      - Library\lib\nvJitLink_static.lib                      # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - sysroot_{{ target_platform }} 2.17    # [linux]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnvJitLink_static.a  # [linux]
        - if not exist %LIBRARY_LIB%\nvJitLink_static.lib exit 1               # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA nvJitLink library
      description: |
        nvJitLink - Just-in-Time Link Time Optimization (JIT LTO)
      doc_url: https://docs.nvidia.com/cuda/nvjitlink/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: CUDA nvJitLink library
  description: |
    nvJitLink - Just-in-Time Link Time Optimization (JIT LTO)
  doc_url: https://docs.nvidia.com/cuda/nvjitlink/index.html

extra:
  recipe-maintainers:
    - adibbley
